networks:
  crud-network:
    driver: bridge
services:
  crud:
    #image: jazzblack/crud-image:1.0.0
    build: ./
    container_name: crud
    ports:
      - '8090:80'
    networks:
      - crud-network

  dbpets:
    image: mysql:9.1
    container_name: dbpets
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: datos
    networks:
      - crud-network
